---
- name: install Apache webserver
  hosts: ubuntu

  tasks:
       - name: install Apache webserver
         apt: name=apache2  state=latest

       - name: restart apache
         service: name=apache2 state=restarted
