---
- name: install Apache webserver
  hosts: all

  tasks:
       - name: Install Nginx
         apt: pkg=nginx state=latest

       - name: Restart Nginx Service
         service: name=nginx  state=restarted

